#!/bin/bash

echo "Railway Deployment Check"
echo "========================"
echo ""
echo "Project ID: ef790873-cffa-4a47-9fad-1e38b317d0c2"
echo ""
echo "To view deployment logs:"
echo "1. Go to: https://railway.app/project/ef790873-cffa-4a47-9fad-1e38b317d0c2"
echo "2. Click on your service"
echo "3. Click on the 'Deployments' tab"
echo "4. Click on the latest deployment to see logs"
echo ""
echo "Common issues to check:"
echo "- Environment variables are set correctly"
echo "- PORT is set to 3001"
echo "- STORAGE_DIR is set to /app/server/storage"
echo "- Service has generated a domain"
echo ""
echo "Your GitHub repo: https://github.com/quinnbmay/anythingllm-railway"